#+title: Test file for OVP

#+BEGIN_SRC elisp :results none
;; Setup:
(setq org-list-allow-alphabetical t)
(org-element-update-syntax)
(org-mode)
#+END_SRC

Pellentesque dapibus suscipit ligula.  Donec posuere augue in quam.
Etiam vel tortor sodales tellus ultricies commodo.

- Suspendisse potenti.  Aenean in sem ac leo mollis blandit.  Donec
  neque quam,
  - dignissim in, mollis nec, sagittis eu, wisi.  Phasellus lacus.
    Etiam

+ [X] Alpha
+ [ ] Beta
  - [ ] Gamma
  - [X] Pseudorandom number generator

a. laoreet quam sed arcu.  Phasellus at dui in ligula mollis ultricies.
  b. Integer placerat tristique nisl.  Praesent augue.  Fusce commodo.

A. laoreet quam sed arcu.  Phasellus at dui in ligula mollis ultricies.
  B. Integer placerat tristique nisl.  Praesent augue.  Fusce commodo.

1. laoreet quam sed arcu.  Phasellus at dui in ligula mollis ultricies.
  2. Integer placerat tristique nisl.  Praesent augue.  Fusce commodo.

| Vestibulum | convallis | , lorem |     |
| a          | tempus    | semper, | dui |
#+TBLFM: 2 + 2 = 4

#+BEGIN_EXAMPLE
(defun doctor ()
  (interactive)
  (kill-emacs))
#+END_EXAMPLE



* TODO dui euismod elit,
[2019-01-24 Prş]

vitae placerat urna tortor vitae lacus.  Nullam libero mauris,
consequat quis,

#+BEGIN_VERBATIM
varius et, dictum id, arcu.  Mauris mollis tincidunt felis.  Aliquam
feugiat tellus ut neque.  Nulla facilisis, risus a rhoncus fermentum,
#+END_VERBATIM

- tellus :: tellus lacinia purus, et dictum nunc justo sit amet elit.
